### PR TITLE
Fix debug build launch

### PR DESCRIPTION
**Pull request by mirh**
Thanks as always to ProcMon

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
I'm going to assume you've tested these changes yourself?

**Comment by mirh** [comment]
*I didn't actually compile the thing and all*, but I found those lines were missing exactly after having noticed that the debug zip was missing one file and nothing was starting.

**Comment by AdrianKoshka** [comment]
Well, for what its worth, your changes _did_ pass the CI builds.

**Comment by RocketLR** [comment]
Cant launch the app in macOS Catalina because the app is not signed by a authenticated developer :(

**Comment by mirh** [comment]
Switch os

**Comment by AdrianKoshka** [comment]
> Switch os

Telling others to switch OS is not a valid solution.

**Pull request merged**
