### PR TITLE
Mention clipboard support in the README

### PR DESCRIPTION
**Pull request by p12tic**
When I was first looking into this repository, the "barrier only supports sharing keyboard and mouse and that's it" information from the README confused me, because it implied no clipboard sharing which is a required feature for me. Only after looking into commit history and diffs I was able to figure out that barrier still supports clipboard sharing. This PR states clipboard support explicitly in the README.

### CODE REVIEW

**Comment by walker0643** [comment]
I'm afraid I don't agree with this one. The readme doesn't have the phrasing that you quoted. It reads: "Barrier will let you use your keyboard and mouse from machine A to control machine B (or more). That's it." This is said in the context of Barrier not aspiring to add all the garbage that Synergy 2 was adding (cloud services, proprietary core rewrites, and I forget what else).

Barrier (and Synergy 1.x) has many features that were side-effects of k/m control and clipboard sharing is one of them. So long as we don't say "it does NOT do clipboard sharing" I don't see why people would think that we removed it from the Synergy 1.x codebase.

**Comment by p12tic** [comment]
>  I don't see why people would think that we removed it from the Synergy 1.x codebase.

Well, somehow I was one of them :-)

As a compromise, could we qualify the "That's it.". I'd propose the following:

> Barrier will let you use your keyboard and mouse from machine A to control machine B (or more). That's it. No cloud services, no proprietary code modules and so on.

By the way, do you agree that the first commit in the PR indeed simplifies the sentence a little?

**Comment by walker0643** [comment]
... no, not really :smile:

IMHO listing the things that Synergy 2.x does (did?) that we obviously think were ill-conceived is unnecessarily adversarial. I have no intention of going to war with the Symless folks or to badmouth them or their work. We just have different ideas about how a product like this should function.

So the real problem you're having is the "That's it." statement? I guess you're seeing the phrase before it as being a complete list of Barrier's features because it leads into "That's it." Would you prefer we swap "That's it." with "It's that simple." so that the phrase's context isn't so vague?

**Comment by p12tic** [comment]
> Would you prefer we swap "That's it." with "It's that simple." so that the phrase's context isn't so vague?

Yes, I think that would completely cover the complaint I had.

**Comment by walker0643** [comment]
Done :)

**Comment by p12tic** [comment]
Thanks!

**Pull request closed without merging**
