### PR TITLE
Add key entries for `Eisu_toggle` and `Muhenkan`

### PR DESCRIPTION
**Pull request by tom-tan**
This request adds key type entries for `Eisu_toggle` and `Muhenkan`, which are used in Japanese keyboards for macOS and Windows computers.
It also adds missing entry of `kKeyNameMap` for `kKeyKana`.

These keys are important for Japanese input methods that input Japanese characters from alphabets (e.g., "ひらがな" from "hiragana").
- `Henkan` and `Muhenkan` are used to enable and disable input methods, respectively in Windows computers.
  - `Henkan` is already available in `key_types.h` and `key_types.cpp`
- `Kana` and `Eisu_toggle` are used to enable and disable input methods, respectively in macOS computers.
  - `Kana` is already available in `key_types.h` but not available in `key_types.cpp`

This request makes easier for Japanese users to share a keyboard between Windows and macOS computers while keeping the functionality of Japanese input methods.

Note: I searched for keysyms for `Eisu_toggle` and `Muhenkan` in the following link: http://wiki.linuxquestions.org/wiki/List_of_Keysyms_Recognised_by_Xmodmap.

### CODE REVIEW

**Comment by shymega** [comment]
Looks sane to me, approving, but going to ask @p12tic to review as well.

**Comment by tom-tan** [comment]
ping!

**Comment by p12tic** [comment]
@tom-tan Many thanks for the pull request!

**Comment by amosbird** [comment]
Hmm, I've built the latest master but still cannot have `Eisu_toggle` mapping in 
image

**Comment by tom-tan** [comment]
As I mentioned in #832, it needs extra work to work these keys in GUI editor.
You can add keystroke settings by editing configuration file directly.

See also: #840.

**Comment by tom-tan** [comment]
$

**Pull request merged**
