### PR TITLE
use pkg-config for finding avahi include dir

### LINKED ISSUE #46: Void Linux dns_sd.h
Sorry I don't know where the template went but this field is completely blank, I saw it for a second but it went away. I'll fill it out if I have to, sorry.

Trying to get Barrier to build on Void Linux (GLIBC) but can't seem to do so, it tells me:

CMake Error at CMakeLists.txt:191 (message):
  Missing header: dns_sd.h

I've installed c-ares c-ares-devel nss-mdns mDNSResponder and any other dependencies I could find... but still get this error.

### PR DESCRIPTION
**Pull request by Johnnynator**
Would resolve #46

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
This would also solve an issue I've been having with the flatpak package.

**Comment by walker0643** [comment]
Thanks, @Johnnynator. Taking a look at it.

**Comment by AdrianKoshka** [comment]
Any news on this?

**Comment by AdrianKoshka** [comment]
This [builds correctly](https://travis-ci.org/debauchee/barrier/builds/399400773) I was wondering if there's a prospect it could be pulled into master? It would solve an issue for me (and others probably).

**Pull request merged**
