### PR TITLE
reimplement how stdin is read on the cli

### LINKED ISSUE #200: Executing barrierc makes terminal line invisible
### Operating Systems ###

Server: Microsoft 10 Enterprise

Client: Ubuntu 18.04

### Barrier Version ###

Windows 10 : 2.1.0-release-0b2dfd80
Ubuntu 18.04 : 2.1.0-snapshot-8b69f9fe

### Steps to reproduce bug ###

1. Open terminal
2. Execute command : barrierc <Your server Address>
3. Bug occurs.

Bug 1 : Terminal output becomes invisible.
Bug 2 : Client doesn't work.

### Other info ###

However, when executing command with --no-daemon option, it worked.
I'd like to add barrierc into Ubuntu Startup Applications Preferences instead of manually starting barrier whenever turning up ubuntu.

Please share your thought

### PR DESCRIPTION
**Pull request by jwestfall69**
This PR re-implements how stdin reading is done on the cli and has the following fixes over the old

1. Doesn't trigger an assert() if running a debug build and in daemon mode
2. Doesn't mess up the terminal if in daemon mode
3. Doesn't listen for stdin input in daemon mode

Fixes #200

### CODE REVIEW

**Comment by p12tic** [comment]
Could we just get rid of listening to stdin? The previous setup of waiting for some symbol is rather uncommon approach and I wonder if that feature is actually used by anyone.

**Comment by p12tic** [comment]
I think I misread your initial proposal of removing listening to stdin in daemon mode in https://github.com/debauchee/barrier/issues/200#issuecomment-450705957 as removing listening to stdin altogether. Sorry for the wasted time :-(

**Comment by AdrianKoshka** [comment]
So should I merge this PR?

**Comment by p12tic** [comment]
No, let's see what @jwestfall69 replies and also we need testing.

**Comment by jwestfall69** [comment]
I was originally hoping to just nuke the stdin reading, but when going through the processing of removing the code I found the GUI was relying on it.  In the GUI when you 'start' its spawning (QProcess) barrierc or barriers as a sub process.  When the user wants to stop in the GUI, the GUI sends the 'S' char to the stdin of the spawned process to signal to it to shutdown/exit.

https://github.com/debauchee/barrier/blob/4dedd88ab2fc900b44cea0003cddf065f01fa521/src/gui/src/MainWindow.cpp#L727-L732

Suppose we could try ditching the stdin bits and just trying to close() the sub process, which the qt docs say will kill it.

**Comment by p12tic** [comment]
Okay, keeping stdin processing makes sense then, for now :-)

The PR looks good to me, just needs testing on windows and osx.

**Comment by jwestfall69** [comment]
I would note that the shutdown process (unrelated to this PR) on OSX results in a segfault, which will make it impossible to fully test this PR.  It happens on both client/server cli binaries and can be seen if you view the logs while hitting the stop button in the GUI

```
[2019-01-05T13:41:24] INFO: stopping barrier desktop process
[2019-01-05T13:41:26] ERROR: process exited with error code: 11
```

**Comment by charliehorse55** [comment]
Hey, can we get this merged? I'm stuck between a rock and hard place right now, since I can't run the barrier GUI since flatpak doesn't support mdns and I can't run the client as a service because of this. I've temporarily fixed it by having it launch in a gui gnome-terminal session on startup, but I'd like to switch it over to a systemd service. 

I have windows, linux and osx vms that I could do some basic tests with need be.

**Comment by AdrianKoshka** [comment]
> I would note that the shutdown process (unrelated to this PR) on OSX results in a segfault, which will make it impossible to fully test this PR.

I'd say this couldn't be merged because of this segfault issue.

**Comment by AdrianKoshka** [comment]
Going to close this PR, if anyone wants to continue the work done here but figure out the segfaulting issue, feel free. I'd suggest opening a new PR though to run against our new CI.

**Comment by jwestfall69** [comment]
Little confused.  You are closing the PR because of a segfault in barrier on OSX unrelated to the PR that makes it impossible to test the PR on OSX?

**Comment by AdrianKoshka** [comment]
I closed this PR mostly due to inactivity.

**Comment by shymega** [comment]
@jwestfall69/others who run Barrier on OSX who has this segfault issue: if you get a chance to get a core dump when it segfaults, please do -- that'd be superb for debugging.

**Comment by jwestfall69** [comment]
I created an issue with some details https://github.com/debauchee/barrier/issues/389

**Comment by shymega** [comment]
FYI, new PR is: #388

**Comment by AdrianKoshka** [comment]
new PR is #390

**Pull request closed without merging**
