### PR TITLE
Update Apt on Linux before installing dependencies on Azure Pipelines

### PR DESCRIPTION
**Pull request by nelsonjchen**

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
All green, nice!

**Comment by nelsonjchen** [comment]
The Windows builds are browning out though. It just happened to work at this moment.

**Comment by AdrianKoshka** [comment]
Ugh… 




Get Outlook for Android







On Sun, May 26, 2019 at 3:21 PM -0400, "Nelson Chen" <notifications@github.com> wrote:












The Windows builds are browning out though. It just happened to work at this moment.

**Comment by nelsonjchen** [comment]
It’s ok now though. #318 was merged in. 🤗

**Pull request merged**
