### PR TITLE
Restore dpiAwareness

### LINKED ISSUE #1462: Windows 10 scaling not supported under certain circumstances
### What happened?

When my Win 10 PC (server, on the left side) is configured to scale to 125%, I cannot use it as a server together with my Mac (client on the right side), because when it moves from one to the other, when arriving to 3/4 of the PC screen, it immediately jumps to the bottom right corner of the Mac and makes the whole sharing useless until I disable the client on the Mac. As soon as I switch to 100% scaling, everything's ok again. So what I did is downgraded the PC to 2.3.4, and it seems to be working fine again, as it was for more than a year with 2.3.3.

### Version

v2.4.0

### Git commit hash (if applicable)

_No response_

### If applicable, where did you install Barrier from?

_No response_

### What OSes are you seeing the problem on? (Check all that apply)

Windows, macOS

### What OS versions are you using?

Server 10.0.19042.1348
Client Monterey 12.0.1

### Relevant log output

_No response_

### Any other information

_No response_

### PR DESCRIPTION
**Pull request by mipedja**
Fixes regression from #304
Fixes #1462, possibly others.

## Contributor Checklist:

* [x] I have created a file in the `doc/newsfragments` directory *IF* it is a
      user-visible change (and make sure to read the `README.md` in that directory)

### CODE REVIEW

**Comment by theofficialgman** [comment]
could you post a windows build here? I would like to verify that this fixes #1415

**Comment by mipedja** [comment]
Here you go:
[BarrierSetup-2.4.0-release.zip](https://github.com/debauchee/barrier/files/7875938/BarrierSetup-2.4.0-release.zip)
[executables.zip](https://github.com/debauchee/barrier/files/7875939/executables.zip)

**Comment by theofficialgman** [comment]
> Here you go: [BarrierSetup-2.4.0-release.zip](https://github.com/debauchee/barrier/files/7875938/BarrierSetup-2.4.0-release.zip) [executables.zip](https://github.com/debauchee/barrier/files/7875939/executables.zip)

Thank you, I tested installer from this `BarrierSetup-2.4.0-release.zip` and it works. This should fix the various reported bugs

**Comment by walker0643** [comment]
Merged. Thanks, @mipedja

**Comment by linussun** [comment]
Great version! Worked for me to connect surfacepro W11 another desktop W11 with 4k monitor at 150%. 

Keeping the filename to 2.4.0 might be confusing, would be great to have this change merged to the next release (which hasn't happened in a while). Is debauchee still active?

**Comment by walker0643** [comment]
HI @linussun - I'm glad to hear that Barrier was able to help you. Yes, Barrier is still active, but we need developers. Barrier has been a great project for us and it has helped a ton of people, but in the absence of help from the community it's been difficult to do everything we want to do. The woes of a community-supported project... :)

If any developers want to volunteer their time, pick an issue that would make Barrier better and submit a PR. After you work with us for a while and if you want to join the team "officially" then tag me in one of your PR comments.

Thanks again and enjoy!

**Comment by back2yes** [comment]
Wow, this build solved my mouse issues freezing at bottom right corner. I'm wondering if there exists any linux builds?

**Comment by livejamie** [comment]
+1 to others this build fixed the bottom right cursor freeze I was experiencing

**Comment by comp1et3noob** [comment]
Hello everyone, I am completely new to GitHub and as my name suggests, I am a complete noob in terms of all of this. I have a similar issue to cursor being stuck when on recommended 125% scale. I have downloaded the packages provided by mipedja and when opening the executables.zip file I see two things: "barrierc.exe" and "barriers.exe". When trying to start these I am hit with the error: "The code execution cannot be proceed because LIBEAY32.dll was not found. Reinstalling the program may fix this problem" and  "The code execution cannot be proceed because SSLEAY32.dll was not found. Reinstalling the program may fix this problem". Do I simply have to find and reinstall these packages? Are they 32-bit Windows specific as I have a Windows 10 64 bit? Any help will be greatly appreciated as I just want to use barrier on my client macos without scaling down to 100%,

**Comment by leavesfish** [comment]
> Hello everyone, I am completely new to GitHub and as my name suggests, I am a complete noob in terms of all of this. I have a similar issue to cursor being stuck when on recommended 125% scale. I have downloaded the packages provided by mipedja and when opening the executables.zip file I see two things: "barrierc.exe" and "barriers.exe". When trying to start these I am hit with the error: "The code execution cannot be proceed because LIBEAY32.dll was not found. Reinstalling the program may fix this problem" and "The code execution cannot be proceed because SSLEAY32.dll was not found. Reinstalling the program may fix this problem". Do I simply have to find and reinstall these packages? Are they 32-bit Windows specific as I have a Windows 10 64 bit? Any help will be greatly appreciated as I just want to use barrier on my client macos without scaling down to 100%,

About this problems, you just need to copy the two two things which are "barrierc.exe" and "barriers.exe" to the installation directory of barrier. Then everything will be ok.

**Comment by F2FG** [comment]
> Here you go: [BarrierSetup-2.4.0-release.zip](https://github.com/debauchee/barrier/files/7875938/BarrierSetup-2.4.0-release.zip) [executables.zip](https://github.com/debauchee/barrier/files/7875939/executables.zip)

I just wanted to add that this build solves the issue with SSL fingerprint creation during the installation too. No need for workarounds. I noticed this while testing the build on a Surface because of the dpiAwareness issue and it was a nice unexpected bonus!

**Comment by LUISTAPIARUIZ** [comment]
Thanks for the solution. I always thought it was Kali that was failing, but it was Windows. Thank you very much.

**Comment by adamyanna** [comment]
Thanks for this build.

**Pull request merged**
