### PR TITLE
[TEST ME!] Smarter Zeroconf Address

### PR DESCRIPTION
**Pull request by walker0643**
Ref: #81

Currently zeroconf code uses Qt libs for picking an IP address to advertise. While it is cross-platform it doesn't prefer real interfaces over virtual ones, nor wired over wifi. This PR fixes both of these issues.

I would like to have the Barrier community test the smartzeroconf branch. Everyone that can use Zeroconf please test with your setup and leave comments below.

If there are issues with detection please use [this project](https://github.com/walker0643/defaultinterfaceip/) as a diagnostic. Windows x64 users can use [this link](https://github.com/walker0643/defaultinterfaceip/releases/download/R1/DefaultInterfaceIP.exe) to download a prebuilt binary.

Thanks everyone!

### CODE REVIEW

**Comment by serussell** [comment]
As I mentioned in another ticket: tested and confirmed on OSX (OSX client, Linux Arch server)

**Comment by AdrianKoshka** [comment]
Would be great if someone tested this for windows...

**Comment by rahuljawale** [comment]
> Would be great if someone tested this for windows...

Can do! Will try to run a few tests over this weekend.

**Comment by AdrianKoshka** [comment]
Thank you very much!

**Comment by rahuljawale** [comment]
@AdrianKoshka I must say I am a bit confused here. Can I use the pre-build barrier binaries or should I build one from this PR?

**Comment by AdrianKoshka** [comment]
Built from this PR.

**Comment by rahuljawale** [comment]
Thanks! I am setting up the build environment at the moment. I will keep you all posted how it goes.

**Comment by serussell** [comment]
I may have spoke too soon.  I may be using it wrong, but I'm seeing some unexpected behavior on OSX.

## Setup

1. zeroconf branch built on both client and server.
2. Server running on Linux
3.  avahi-daemon running on the server
4. "Ignore auto config clients" **disabled**
5. Client running on OSX

## Server

I don't see any service that looks like Barrier using `avahi-browse` or `avahi-discover`. 

## Client

1. Leaving the server IP field blank and turning on "Auto" on results in a message about needing the IP field filled in.  
2. Running `barrierc` on the command line insists on having a server name argument

## Questions

1. How can I run the client in auto-discover mode?
2. How can I prove that the `barrier` is advertizing itself?
3. Do I need to enable Zeroconf in the build process?

**Comment by AdrianKoshka** [comment]
> 1. How can I run the client in auto-discover mode?
> 2. How can I prove that the barrier is advertizing itself?
> 3. Do I need to enable Zeroconf in the build process?
1. To my knowledge, the client does this by default
2. I don't know, sorry.
3. I'd assume so.

**Comment by rahuljawale** [comment]
I concur @serussell 's findings. 
### Setup
smartzeroconf branch built on Windows 10 Pro (Azure VM) using VS 2019
Server is running on MacOS X
Client running on Windows 10 Pro

### Server
MacOS X Mojave patches to latest.
Barrier 2.2.0 binary built using flatpack

### Client
I keep getting the popup asking me to fill Server hostname to connect to.

### DefaultInterfaceIP.exe output
Can see that it is picking up virtual interface and not the physical one.
`Adapter 1:
  Name:{480E00CA-438A-4C1D-99FD-7CC760468257}
  Description: Intel(R) Ethernet Connection I217-LM
  Unicast Address: 169.254.42.117
  Not Up (2)
  Wired
Adapter 2:
  Name:{7241463E-35F3-4435-9B0A-E4DA6851A2E2}
  Description: VirtualBox Host-Only Ethernet Adapter
  Unicast Address: 192.168.56.1
  Up
  Wired
  Selecting as default
Adapter 3:
  Name:{607B8CBA-02AE-49FF-A3D2-B195EDB5C47C}
  Description: Intel(R) I210 Gigabit Network Connection
  Unicast Address: 10.0.0.50
  Up
  Wired
Adapter 4:
  Name:{A9651781-D965-11E7-ACFE-806E6F6E6963}
  Description: Software Loopback Interface 1
  Unicast Address: 127.0.0.1
  Up
  Loopback

Default IP Address (v): 192.168.56.1
Default IP Address (q): 169.254.42.117`

### Triage Steps
Tried providing server ip address and I was able to control my Windows desktop using MacBook keyboard and mouse.
Turned off firewall on Windows machine.
Bonjour service is up and running
Can ping the IP address of the server

**Comment by rahuljawale** [comment]
Something weird happened. I closed Barrier and started again and I was able to see IP dropdown with my server LAN address. But it also displays virtual network IP. Will that be a defect?

**Comment by noisyshape** [comment]
The UI is poorly designed so let me explain how autoconfig is supposed to work. When you check the autoconfig box, that is effectively the start button for autoconfig mode. The Main Barrier application will look for a server advertised on the network. When it finds one, it gets added to a list and starts/restarts the client. If you press start, Barrier will try to start a client. If you don't have a server list from autoconfig, the manually entered server IP address will be used as a fallback. There's no indication that this is happening and no autoconfig-specific error message. If you get a message telling you to specify a server, autoconfig was not successful.

I haven't had success with autoconfig myself. To test autoconfig, I would recommend that you clear the server IP field and use a separate zeroconf browser to monitor what's being advertised on the network.

**Comment by serussell** [comment]
I'm not seeing the same behavior, regrettably.  If I:

1. Stop barrier (using the client)
2. Clear the Server IP field (in the client)
3. Check the Auto config box
4. Exit barrier (client)
5. Start the client

I don't get the drop down.  OTOH, I **was** trying to find barrier on the Avahi server, and wasn't seeing any service, so it may be that the server isn't advertising itself. 

@noisyshape, is there any way I can debug the Zeroconf process in the server and make sure it's (a) trying to register itself, and (b) see why the registration is failing?

**Comment by noisyshape** [comment]
> @noisyshape, is there any way I can debug the Zeroconf process in the server and make sure it's (a) trying to register itself, and (b) see why the registration is failing?

@serussell I haven't dug into the client/server source much, but I think zeroconf is strictly a feature of the main GUI application. I don't know why, except that that's how the feature was bolted on. What you would need to debug is src/gui/src/ZeroconfService.cpp. You can add some debug messages with qDebug or just append to the log. To know for sure what's going on I think you'll need to do packet capture with something like wireshark.

**Comment by rahuljawale** [comment]
@serussell, can you try running the binary provided in the first post of
this thread? I *think* that made the difference for me.

**Comment by serussell** [comment]
@rahuljawale No Windows in this household, so the binary won't help me.  It's all Linux & Macs.

@walker0643 Does the build require any special arguments or settings to enable Zeroconf?

**Comment by AdrianKoshka** [comment]
I don't think it requires anything special, no.

**Comment by rahuljawale** [comment]
@serussell , I have all three. Do you need help building one on any of these platforms? I could give it a try if you need.

**Comment by rahuljawale** [comment]
Here you go : https://github.com/rahuljawale/defaultinterfaceip/releases/tag/R1

MacOS X Mojave : MD5# 078097698ef3c97a2624c4a84cc9f546
Linux : MD5# be231b971ddd22c723d02231fdc9b6f8

**Comment by serussell** [comment]
Incidentally (maybe relevant?):

```
*** WARNING *** The program 'barrier' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
("-f", "--no-tray", "--debug", "WARNING", "--name", "glamdring", "--enable-crypto", "-c", "/tmp/Barrier.WevvzL", "--address", ":24800")
```

Could this explain the fact that I'm seeing issues between a Linux barrier server and a MacOS barrier client?

**Comment by AdrianKoshka** [comment]
Maybe, we don't have propper avahi support on linux unfortunately.

**Comment by serussell** [comment]
Ok, so:

My server happens to have two IP addys: `192.168.0.16`, `192.168.0.18`
My client has one IP: `192.168.0.12`

The tool on the server returns:

```
Interface 4
  Name: lo
  Address: 127.0.0.1
  Up
  Running
  Loopback
  Wired

Interface 5
  Name: wlp2s0
  Address: 192.168.0.16
  Up
  Running
  Wireless
  Selecting as wireless

Interface 6
  Name: ens12u1u1u1
  Address: 192.168.0.18
  Up
  Running
  Wired
  Setting as default

Default IP Address (v): 192.168.0.18
Default IP Address (q): 192.168.0.18
```

On the client:

```
Interface 2
  Name: lo0
  Address: 127.0.0.1
  Up
  Running
  Loopback
  Wired

Interface 10
  Name: en0
  Address: 192.168.0.12
  Up
  Running
  Wireless
  Selecting as wireless

Default IP Address (v): 192.168.0.12
Default IP Address (q): 192.168.0.12
```

I ran this, BTW, when I had barrier running and working when the IP address has been manually entered.

So, it looks like ZeroConf isn't working for me, antd maybe it's because of that warning message I posted previously.

**Comment by AdrianKoshka** [comment]
I remember speaking to an avahi dev once who said they might add full support for barrier if they ever go the time. Guess they didn't or forgot.

**Comment by rahuljawale** [comment]
> Ok, so:
> 
> My server happens to have two IP addys: `192.168.0.16`, `192.168.0.18`
> My client has one IP: `192.168.0.12`
> 
> The tool on the server returns:
> 
> ```
> Interface 4
>   Name: lo
>   Address: 127.0.0.1
>   Up
>   Running
>   Loopback
>   Wired
> 
> Interface 5
>   Name: wlp2s0
>   Address: 192.168.0.16
>   Up
>   Running
>   Wireless
>   Selecting as wireless
> 
> Interface 6
>   Name: ens12u1u1u1
>   Address: 192.168.0.18
>   Up
>   Running
>   Wired
>   Setting as default
> 
> Default IP Address (v): 192.168.0.18
> Default IP Address (q): 192.168.0.18
> ```
> 
> On the client:
> 
> ```
> Interface 2
>   Name: lo0
>   Address: 127.0.0.1
>   Up
>   Running
>   Loopback
>   Wired
> 
> Interface 10
>   Name: en0
>   Address: 192.168.0.12
>   Up
>   Running
>   Wireless
>   Selecting as wireless
> 
> Default IP Address (v): 192.168.0.12
> Default IP Address (q): 192.168.0.12
> ```
> 
Looks like your server has two IP addresses, one through wired and another through wireless. May be you can try disconnecting one?

**Comment by payomagic** [comment]
Win10 x64 Pro
-- the Zerconf chooses as default a VMWare virtual interface... not physical incl. wired 
-- Snappy from snapcraft store installed in devmode on Ubuntu x64 -> both server/client works with zeroconf ok + no errors being thrown out (ok also in SSL mode)
----------------------------------------
Win10 x64 Pro - defaultInterfaceIP
Adapter 1:
  Name:{6E410D0C-7CC3-4C60-9E9E-274EBAFDF2B1}
  Description: Broadcom 802.11n Network Adapter
  Unicast Address: 10.11.10.88
  Up
  Wireless
Adapter 4:
  Name:{48A917BE-3721-438E-9DAA-157749FB1912}
  Description: VMware Virtual Ethernet Adapter for VMnet1
  Unicast Address: 192.168.159.1
  Up
  Wired
  Selecting as default
Adapter 5:
  Name:{F07D947C-FDC5-4076-A055-AB3EE543B5A8}
  Description: VMware Virtual Ethernet Adapter for VMnet8
  Unicast Address: 192.168.87.1
  Up
  Wired
Adapter 6:
  Name:{DA9B2BFF-F959-4CE9-924F-0099ED0CC305}
  Description: Intel(R) 82579V Gigabit Network Connection
  Unicast Address: 10.11.10.22
  Up
  Wired
Adapter 14:
  Name:{94DB2B9C-C8ED-11E8-9702-806E6F6E6963}
  Description: Software Loopback Interface 1
  Unicast Address: 127.0.0.1
  Up
  Loopback

Default IP Address (v): 192.168.159.1
Default IP Address (q): 192.168.159.1

**Comment by AdrianKoshka** [comment]
Going to close, then re-open under a new PR to run against new CI, just in-case anyone is still interested.

**Comment by ArntWork** [comment]
I wonder if it would not be possible to simply sent all these addresses to the client, and let it try which one it can connect over (and retry all of them if the connection fails, e.g. if I turn off wifi)?

**Pull request closed without merging**
