### PR TITLE
fix(macos-build): Use standard methods for detecting XCode installation and macOS SDK

### PR DESCRIPTION
**Pull request by sidneys**
This Pull Request replaces the
 1. hard-coded XCode installation path (`/Applications/Xcode.app`)
 1. hard-coded macOS SDK (`MacOSX10.13.sdk`)
by standard macOS methods for automatic lookup of both requirements.

Kind regards & Thank you for a great fork,
S

### CODE REVIEW

**Comment by walker0643** [comment]
Thank you, @sidneys. Are we just patching to be correct or does this fix an issue you were having? If so can you give more details?

**Comment by sidneys** [comment]
Hi @walker0643

You're welcome, appreciate the quick feedback 🏎🏎🏎🙆🏾‍♂️

My reliance on `xcode-select` prevents a problem on macOS/iOS systems on which it's typical (especially in CI environments) to have multiple versions of XCode installed (due to Apples policy of quickly dropping for support older SDKs in newer XCodes...), and a simple reliance on the default app path would yield a wrong arbitrary XCode installation (or fail completely if the user has switched to `XCode-beta.app`). Thus, the build failed on both of my development machines before the tweak.

The change to the macOS SDK lookup enables the app to be built on more XCode versions (7/8/9/10b), whereas the previous hardcoded symlink (`/SDKs/MacOSX10.13.sdk`) requires a XCode 9 installation (as only XCode 9 ships with `MacOSX10.13.sdk`). I tested the build on a 10.14/XCode 10b machine, which worked flawlessly afterwards (same on 10.13/XCode 9).

Kind regards,
S

**Comment by p12tic** [comment]
This PR LGTM.

**Comment by walker0643** [comment]
Sold. Thank you, @sidneys!

**Pull request merged**
