### PR TITLE
Proposal: Replace bundled gtest directory with Git submodule

### PR DESCRIPTION
**Pull request by shymega**
This PR replaces the bundled `/ext/gtest` directory with a Git submodule locked at the same release as before - 1.6.0 - but it should be considered to bump the release in the near future when and if possible.

Thoughts?

### CODE REVIEW

**Comment by shymega** [comment]
Oh, I can see CI is failing. Probably because the CI scripts don't initialise and pull Git submodules. Will look into it.

**Comment by shymega** [comment]
OK, that looks like it works with CI now. Thoughts, anyone? CC: @the-wes, @p12tic

**Comment by shymega** [comment]
Just removed the `ext/gmock` directory, as the new `ext/gtest` submodule actually contains both Google Mock and Google Test now. So we'll need to factor that into the testing as well, and possibly consider whenever to keep either/both of them.

**Comment by shymega** [comment]
Oh, wait, that's a mistake.. v1.6.0 hasn't made that change yet. I messed up there.

OK, will revert that last commit, and add gmock again. Sorry!

**Comment by shymega** [comment]
OK, made some more mistakes, but should be fixed now. I've locked Google Mocking at v1.6.0.

To give some clarification, Google Testing now has mocking in the same project, and the Google Mock repo is now archived, but the v1.6.0 tag still exists.

I've created another Git submodule for gmock. My previous commits were mistaken, and I had messed it up a bit. Its late at night for me, and I think my code quality is suffering!

**Comment by shymega** [comment]
Possibly should squash those last few commits into one..

**Comment by p12tic** [comment]
> Possibly should squash those last few commits into one..

Yeah, I really need `git rebase master` in this case :)

**Comment by shymega** [comment]
I was just gonna squash and merge with the GitHub UI tbh.

**Comment by shymega** [comment]
Merging in a sec. Is that alright, @p12tic - we good to go?

**Comment by p12tic** [comment]
Rebased on latest master. Looking into commits again, not all commits need squashing, as that would remove information.

**Pull request merged**
