### PR TITLE
Make Barrier work over Bluetooth sockets.

### PR DESCRIPTION
**Pull request by ali1234**
I don't expect you to merge this but I wanted to draw your attention to it, and ask if you are interested in this functionality.

This patch makes barrier run over RFCOMM bluetooth sockets. This is useful for a number of reasons:    

 * It is encrypted by default.
 * It is "out of band" - meaning you won't lose control if the network connection goes down or is swamped by a large file transfer.
 * SDP allows a laptop running the client to "roam" between two or more servers, eg home and work.

It is adapted from synergy-bluetooth which I created nearly 10 years ago with assistance from Valmantas Palikša aka @walmis, who was the maintainer of Blueman at the time. I had thought the code lost, but I was inspired to go looking again with the release of Barrier. I have ported the old code to Barrier and tested that it still works. Unfortunately the change history and attribution is definitely lost, unless walmis has it.

This is Linux-only, and currently breaks TCP socket implementation.

To use it you must run bluetoothd with --compat and give yourself
write access to /var/run/sdp. The SDP code will need to be ported
to the new DBUS implementation to fix this.

No changes are needed in the server config file.

The client can be run with no arguments. It will scan for a server
using SDP. Alternatively a BDADDR can be supplied (run hciconfig
on the server to find it). This mode of operation is more reliable
and does not require the server to be discoverable. However, SDP
scanning allows a client to roam between servers seamlessly.

The SDP code is copyright (C) 2009 Valmantas Palikša.

The trick here is that bluetooth sockets are nearly interchangable with AF_INET sockets on Linux. Also, since the addition of ipv6, there is already support for two different AF socket families and the ability to select which address family to use in many (but not all) parts of the code. AF_BLUETOOTH only really requires slightly different name resolution and everything else works the same. In fact TCPListenSocket already works with AF_BLUETOOTH with no modifications, so maybe its name is not entirely accurate. ;)

The most obvious problem with this patch is that it currently replaces TCP/IP function. In the Ipc classes, and in some other places, the choice of address family is hardcoded. Rather than try to add run time selection like the old version did, I have simply changed them all to kBLUETOOTH. However, in many other places, adding support is as simple as adding another case: to a switch statement.

There is also the issue of SDP. This makes up the bulk of the patch. In Bluez 5 the API used here is deprecated, replaced by a DBus protocol. This may mean a dependency on glib or some other DBus handling library.

### CODE REVIEW

**Comment by walker0643** [comment]
@ali1234 - Are we still working on this PR??

**Comment by ali1234** [comment]
I'm not really sure how to proceed with this. There are two problems:

1. The remaining breaking changes are quite small, but I think fixing them would need quite a lot of refactoring. I'm not sure how to approach it wrt creating a new option and exposing it to the user. This is a user interface design problem, and I am no good at that stuff. I also don't know how the GUI works at all. I have only ever used synergy by writing a config file and launching synergyc/synergys from the command line.

2. The SSDP code is supposed to be replaced by DBus calls. Without porting to DBus, making it work requires enabling legacy bluetooth support in the operating system, which is difficult and annoying for the user. The problem here is that DBus is really annoying for developers, and I don't have time at the moment to re-learn how to do it in C code.

**Comment by p12tic** [comment]
> The problem here is that DBus is really annoying for developers, and I don't have time at the moment to re-learn how to do it in C code.

Just a nitpick: you don't need to do DBus integration in C, there's C++ wrapper in Qt: https://doc.qt.io/qt-5/qdbusconnection.html

**Comment by walker0643** [comment]
@ali1234 Should we drop this for now? We can always resume if you find more time in the future.

**Comment by ali1234** [comment]
Yes, lets close it for now.

**Pull request closed without merging**
