### PR TITLE
Azure pipelines

### LINKED ISSUE #293: Move to Azure Pipelines
It was suggested in #250, that we could move to Azure Pipelines as solution to building on all three platforms under one roof. @nelsonjchen originally suggested this.

### PR DESCRIPTION
**Pull request by nelsonjchen**
Closes #293 

WIP. Broken stuff, Messy commits, needs rebase, yadda yadda.

Builds Link: https://dev.azure.com/nelsonjchen/Barrier/_build?definitionId=14&_a=summary

### CODE REVIEW

**Comment by nelsonjchen** [comment]
First "hey i'm building it for all platforms"! Debug and Release Windows Target and the installer too. I also translated the travis.yml for Azure for the Linux and Mac Homebrew build. 

https://dev.azure.com/nelsonjchen/Barrier/_build/results?buildId=290 

[Unfortunately, the pipelines unlimited storage thing is no longer offered](https://devblogs.microsoft.com/devops/a-simpler-way-to-buy-azure-devops/). I can still use it for 12 months of grandfathering but new organizations cannot. I'll have to take a look again at how we can cache or greatly accelerate QT installation on Windows or maybe we'll just have to pay extra attention to how much space we're using in that.

**Comment by nelsonjchen** [comment]
You can click on the Artifacts Button to download the Windows artifacts.

artifacts link

**Comment by nelsonjchen** [comment]
I'm also currently unfamiliar will be the Mac and Linux build artifacts. I'll also need to investigate what those exactly are as well.

**Comment by nelsonjchen** [comment]
For the QT issue, I'm going to investigate if [CuteCI](https://github.com/hasboeuf/cuteci) will work for Windows and if it doesn't, fix it to.

**Comment by AdrianKoshka** [comment]
Do you think we should try to utilize release pipelines? Idk much about Azure pipelines, haven't had too good of experiences trying to set it up in the past for other projects.

**Comment by nelsonjchen** [comment]
I'm just interested in getting that damned ❌out of the commits on GitHub and the pull request and a releases page in this repo with versions that include builds for all supported platforms where the repository has tagged things, [like with the build pipeline for the mDNSresponder builds I've been doing](https://github.com/nelsonjchen/mDNSResponder/releases/tag/v2019.05.08.1).  That release was created by simply creating a tag and letting Azure Pipelines add the release information. 

The releases pipeline functionality is nice for blue-green deployments and business requirements such as approvals. It's another layer though. I don't see the need for such so this by itself should be fine. 

If this changes, I can send more PRs in. For now, I just want to address the ❌s and the Releases page. 

That said, if barrier ever decides to make a HTTP website, I wouldn't mind doing what the [OpenRCT2 people are doing for their downloads page](https://openrct2.org/downloads).

**Comment by AdrianKoshka** [comment]
Ah, okay, I see. Fair enough.

**Comment by AdrianKoshka** [comment]
Oh, well, this is unfortunate. I don't have permission to install azure-pipelines form the github marketplace for this organization. This will obviously throw a wrench in things...ugh.

**Comment by nelsonjchen** [comment]
🤞

**Comment by nelsonjchen** [comment]
On the QT front, I found, mirrored, and adjusted an alternate installer:

https://github.com/nelsonjchen/qli-installer

Initial tests show it to install what we need from QT in about 14 seconds.

**Comment by AdrianKoshka** [comment]
Wow, I'm impressed, good job!

**Comment by nelsonjchen** [comment]
With my modification of @lnjX's QT installer script which I've plumbed with a bit more Windows support, parallelization, environment variable options for temporary and output directories, and automated testing, we can install QT5 from scratch on Windows is 21 seconds on Azure Pipelines and I'm able to successfully build barrier from these downloaded and installed files on Windows:

https://dev.azure.com/nelsonjchen/Barrier/_build/results?buildId=323

**Comment by nelsonjchen** [comment]
🤞 we can get in contact with @walker0643

**Comment by AdrianKoshka** [comment]
So far, it isn't looking good…

**Comment by AdrianKoshka** [comment]
Do you know if Azure Pipelines can be integrated with Github Release? As in, on a tagged build, Azure Pipelines builds for all the platforms, and then creates a github release and uploads the resulting binaries as assets?

**Comment by nelsonjchen** [comment]
Definitely! I did it for the mDNSresponder pipeline.

**Comment by TafThorne** [comment]
If we get really stuck and unable to contact @walker0643 then maybe we need to fork and setup a barrier organisation with at least 2 or 3 people that have owner permissions in them.  Hopefully we could get hold of them and perhaps get @AdrianKoshka bumped up the ranking to be able to do almost anything in this repo.

**Comment by AdrianKoshka** [comment]
@nelsonjchen So is everyone ready to be merged on your end?

**Comment by AdrianKoshka** [comment]
> Hopefully we could get hold of them and perhaps get @AdrianKoshka bumped up the ranking to be able to do almost anything in this repo.

Yeah, this is what I'd rather do tbh, but it's not up to me to make that decision.

**Comment by walker0643** [comment]
@nelsonjchen - Which type would you like? 
pipeline

**Comment by nelsonjchen** [comment]
Starter Pipeline. 

It'll make an `azure-pipelines` branch and a pull request. Just use the defaults. It's noise but I can't figure out any other way to hook up Azure Pipelines without letting a bit of crap into the repo. Luckily, we can just close/delete those after.

**Comment by nelsonjchen** [comment]
@AdrianKoshka I would like to rebase and squash first. The branch still has scars from the caching approach which we ultimately did not use. I'll try to do that sometime this evening after the day job. That's why I've left it as a draft pull request 😃 . 

I do not have the GitHub releases integration or the Mac/Linux artifacts done yet. That'll require further administrative work on @walker0643 's part to add a GitHub connection. I think we should just save that for another pull request. I'm ok with just getting the ❌ s out and redundancy off Travis.

**Comment by AdrianKoshka** [comment]
So we're ready? This can finally be merged?

**Comment by AdrianKoshka** [comment]
Alrighty, just let me know when to hit the button!

**Comment by nelsonjchen** [comment]
I also found out there's another fork of @lnjx's QLI Installer that pretty much does what my fork does and is quite a bit more polished. 😒

https://pypi.org/project/aqtinstall/

It'll also have to be for another pull request.

**Comment by AdrianKoshka** [comment]
Sounds like you have your work cut out for you. :D

**Comment by nelsonjchen** [comment]
Cool, it looks like it's building. 

I think this is ready for review. @AdrianKoshka .

**Comment by AdrianKoshka** [comment]
Awesome!On May 15, 2019 23:29, Nelson Chen <notifications@github.com> wrote:Cool, it looks like it's building.
I think this is ready for review. @AdrianKoshka .

**Comment by TafThorne** [comment]
Looks good: 
Working Azure & Travis CI

**Pull request merged**
