### PR TITLE
Use noexcept instead of dynamic exception specifications

### PR DESCRIPTION
**Pull request by p12tic**
This PR changes code to use `noexcept` exclusively. Dynamic exception specifications have been removed completely out of C++20. Also macros such as `_NOEXCEPT` have been replaced with `noexcept`.

This PR depends on #717 to fix build issue due to missing #include.

### CODE REVIEW

**Comment by shymega** [comment]
This has a merge conflict.. could you fix that, and push to the PR once done? Cheers.

Also, are we definitely supporting C++20 now as a minimum?

**Comment by p12tic** [comment]
`noexcept` is from C++11, I only mentioned that we were using features that are not only deprecated, but removed from a future version of the standard.

**Comment by shymega** [comment]
> `noexcept` is from C++11, I only mentioned that we were using features that are not only deprecated, but removed from a future version of the standard.

Gotcha. Alright, just wanted to check really. Although, perhaps we should set a minimum C++ version... that's food for thought though. Merging now :smile:

**Comment by p12tic** [comment]
We default to C++14 right now.

**Comment by shymega** [comment]
OK. Would you say that's alright for now? Of course we need to factor in portability...

**Comment by p12tic** [comment]
Yes. I think we should wait until we have a good use case for a newer standard before thinking about a upgrade. At this moment I don't see any features that would be beneficial.

**Comment by shymega** [comment]
Alright, thanks for your input; sounds like a plan!

**Pull request merged**
