### PR TITLE
Let tray image blend into macOS menu bar

### PR DESCRIPTION
**Pull request by tiwoc**
The [expected style](https://developer.apple.com/design/human-interface-guidelines/macos/extensions/menu-bar-extras/) for macOS menu bar images is a template image than can adapt to the user's appearance settings. Also, high-res screens ("Retina" in Apple speak) need higher resolution images.

Without this PR (Light Mode):
before-light
Without this PR (Dark Mode):
before-dark

----

With this PR (Light Mode):
after-light
With this PR (Dark Mode):
after-dark

Based on /res/barrier.svg, I created black and transparent SVGs for the three icon states. I had to remove some details to make the image scale down to icon size without becoming too crowded, and I drew a new checkmark and the transfer arrow.

### CODE REVIEW

**Comment by simons-public** [comment]
@tiwoc Thanks, this makes the menu bar icon so much better

**Comment by cschep** [comment]
This looks awesome, is this part of any releases or do I need to run master to pick up this change?

Really nice, thanks @tiwoc !

**Comment by simons-public** [comment]
@cschep It's not in any of the releases, but you can get it in a compiled release of master from the [published artifacts](https://dev.azure.com/debauchee/Barrier/_build/results?buildId=182&view=artifacts&type=publishedArtifacts) on Azure.

**Comment by AllesMeins** [comment]
Is this only for the mac-version or is it the new standard for all versions? I'm running barrier on Linux (KDE) and I've been looking for a way to get a monochrome icon for quite some time...

**Comment by tiwoc** [comment]
This PR did only affect the Mac icon, that's right. It should be pretty easy to apply a similar change for Linux if a black and white icon fits the predominant style across the common desktop environments. I unfortunately don't have the time to do (and test) that, though.

**Pull request merged**
