### PR TITLE
translation: ja-JP 

### PR DESCRIPTION
**Pull request by maboroshin**
There was untranslated parts. Previous translation status:

b2

I translated. I also added barrier's resources and compiled and checked. The following is a completed Japanese translation.

b1

### CODE REVIEW

**Comment by shymega** [comment]
How is the translation going, @maboroshin? Looking forward to the translation :smile:

**Comment by maboroshin** [comment]
@shymega Hi! Translation into Japanese is completed with this PL. It is the second image. Other parts have been resolved as well.

Previously, my PL did not add new resources.

**Comment by maboroshin** [comment]
synergy-core did not reply to me. Updated language files with the release of Stable 1.11.1 yesterday. For this reason, I got to know the translation site and translated it. Thus, it is not translated in 1.11.1. But the translations are almost the same.

I'm also ready to translate for Barrier.

**Comment by shymega** [comment]
Hi, feel free to translate Barrier, I'll merge this in when you're ready; no rush!

Thanks!

**Comment by maboroshin** [comment]
This issue is active.

**Comment by p12tic** [comment]
Rebased on top of newest master and resolved a couple of merge conflicts.

**Pull request merged**
