### PR TITLE
Alter clean_build.sh to build on macOS.

### PR DESCRIPTION
**Pull request by go8ose**
This is the change that haken-theren suggested in bug #756, to allow building of barrier on macOS.

### CODE REVIEW

**Comment by go8ose** [comment]
Hmm. Maybe the next step is to patch the clean_build.sh script so that my change only occurs for Catalina and later systems.

**Comment by shymega** [comment]
If anyone has a Mac device, we'd welcome test son various versions of the OS in relation to this PR...

**Comment by fdelucchijr** [comment]
I have macOS M1 MBA, happy to test it. At first glance gets this:

```
CMake Error at /opt/homebrew/Cellar/cmake/3.20.5/share/cmake/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/../Documents/Proyects/BarrierNative/orignial/barrier/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/make -f Makefile cmTC_560a4/fast && /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_560a4.dir/build.make CMakeFiles/cmTC_560a4.dir/build
    Building C object CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc   -arch arm64 -mmacosx-version-min=10.9 -MD -MT CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -c /Users/.../Documents/Proyects/BarrierNative/orignial/barrier/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_560a4
    /opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_560a4.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc  -arch arm64 -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/opt/homebrew/opt/qt@5/lib  CMakeFiles/cmTC_560a4.dir/testCCompiler.c.o -o cmTC_560a4
    ld: library not found for -lSystem
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_560a4] Error 1
    make: *** [cmTC_560a4/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
 CMakeLists.txt:19 (project)
```

**Comment by shymega** [comment]
Related to #1385 - let's continue the discussion there for now.

**Pull request closed without merging**
