### PR TITLE
Fix #232 MACOS serious config file errors - hotkeys totally broken

### LINKED ISSUE #232: MACOS serious config file errors - hotkeys totally broken
Server: MACOS 10.13.6
Client: Windows 10 Pro

UPDATED:

Solved that issue by removing switchDoubleTap = 250.

To clarify, the only issue I'm unable to get past now is getting hotkeys to work at all. None of them will do anything, seemingly no matter the config.

If anyone has some advice for how to approach this, please pipe in.

UPDATE:
Now have hotkeys working on client side only. All hotkeys on server side are ignored by Barrier.
Additional info:
All hotkeys using modifiers (CTRL, ALT, SHIFT etc) are ignored and do not register as an input in Barrier.
All single-key hotkeys (, E, 5 etc) are effective to change the active screen from client to server ONLY.

All other uses of hotkeys are ignored by Barrier.

### PR DESCRIPTION
**Pull request by wangchun**

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
I assume you've tested this fix yourself?

**Comment by AdrianKoshka** [comment]
For anyone who wants to test the fix

[Mac Release Disk Image and App.zip](https://github.com/debauchee/barrier/files/3291586/Mac.Release.Disk.Image.and.App.zip)

**Comment by p12tic** [comment]
@wangchun: Thanks for your contribution. Could you explain what you found is causing the bug and how your PR fixes that issue?

**Comment by wangchun** [comment]
> @wangchun: Thanks for your contribution. Could you explain what you found is causing the bug and how your PR fixes that issue?

I don't know. It was not from me. I got this patch from a never-been-merged pull request at the synergy project. It shocks me why this patch could never get merged over there. It looks like nobody cares of their paid users. After all, this patch fixes the issue.

**Comment by p12tic** [comment]
Could you give a link to that pull request?

**Comment by wangchun** [comment]
https://github.com/symless/synergy-core/pull/5522/files I think so.

I though it's been merged but I checked the latest master it's not. I downloaded the latest version of synergy hotkey not working there.

**Comment by p12tic** [comment]
Adding proper link so that github links the two PRs together: https://github.com/symless/synergy-core/pull/5522.

**Comment by AdrianKoshka** [comment]
It worked at the time of writing (2014), so should we assume it still works now? I don't see any reason it shouldn't.

**Comment by wangchun** [comment]
Yes, it works with the latest codebase. I've been using this patch for a month now. I found this software back in 2007 almost gave it up due to this bug.

**Comment by p12tic** [comment]
The change is effectively removal of a single if and there's plenty of evidence it works.

**Comment by AdrianKoshka** [comment]
Fair enough, I'll merge it then.

**Pull request merged**
