### PR TITLE
Windows installer fix

### PR DESCRIPTION
**Pull request by noisyshape**
Fix for #286. build_installer.bat now works. Steps for building the installer:

1. Install Wix Toolset 3.11
2. Create a Release build with clean_build.bat
3. Run build_installer.bat

You should then have an MSI installer in build/installer-wix/bin/. It does not detect or uninstall the 2.1.0 release. It needs to be tested for other issues.

### CODE REVIEW

**Comment by AdrianKoshka** [comment]
Will test when I have the time to. :)

**Comment by noisyshape** [comment]
I've found out that the Wix installer uses Synergy's application GUID which means it will uninstall Synergy and do who knows what else. It's trivial to build the Inno installer instead, but I don't think either should be distributed without someone reviewing the installer code. I don't know anything about Wix or Inno but I've started that review.

**Comment by AdrianKoshka** [comment]
> I've found out that the Wix installer uses Synergy's application GUID which means it will uninstall Synergy 

That is certainly an issue.

**Comment by noisyshape** [comment]
I finished my review of everything in dist/inno. It's very straight forward and readable. All of the Barrier-specific configuration is in barrier.iss.in. Everything else is from third parties and the only blind spot is isxdl.dll which I couldn't find documentation or source code for.

Wix might be cleaner but it's also harder to understand and since the Wix configuration hasn't been updated from Synergy, I replaced Wix with Inno in the installer build script. I tested the Inno Installer on Windows 10 by installing fresh, upgrading from 2.1.0, downgrading to 2.1.0, and installing alongside Synergy. It behaves just like the 2.1.0 release.

To build a 2.2.0-Release installer:
1. Install Inno Setup 5
2. Set B_BUILD_TYPE=Release and BARRIER_VERSION_STAGE=Release in build_env.bat
3. Run clean_build.bat
4. Run build_installer.bat

**Comment by AdrianKoshka** [comment]
Thanks, will probably test this tomorrow, totally forgot.

**Comment by AdrianKoshka** [comment]
The installer executable is `barrier-windows-installer-fix\build\installer-inno\bin\BarrierSetup-2.2.0-snapshot.exe`, correct?

**Comment by noisyshape** [comment]
Correct. That installer will identify itself as 'Barrier 2.2.0-snapshot'. If you want it to say release, you have to set BARRIER_VERSION_STAGE.

**Comment by AdrianKoshka** [comment]
> If you want it to say release, you have to set BARRIER_VERSION_STAGE.

Odd...thought I had.

**Comment by AdrianKoshka** [comment]
Ah, got it working!

`C:\Users\alc\Desktop\barrier>dir build\installer-inno\bin\BarrierSetup-2.2.0-Release.exe`

**Pull request merged**
